chore: enable v3 base e2e test case on pr

diff --git a/.github/workflows/e2e-test.yml b/.github/workflows/e2e-test.yml
--- a/.github/workflows/e2e-test.yml
+++ b/.github/workflows/e2e-test.yml
@@ -150,6 +150,83 @@ jobs:
           version=$(node -p -e "require('./packages/cli/package.json').version")
           npx ts-node .github/scripts/testPlan.ts new cli $version
 
+  execute-base-case-v3:
+    if: ${{  github.event_name == 'pull_request' }}
+    runs-on: ubuntu-latest
+    env: 
+      AZURE_ACCOUNT_NAME: ${{ secrets.TEST_USER_NAME }}
+      AZURE_ACCOUNT_OBJECT_ID: ${{ secrets.TEST_USER_OBJECT_ID }}
+      AZURE_ACCOUNT_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
+      AZURE_SUBSCRIPTION_ID: ${{ secrets.TEST_SUBSCRIPTION_ID }}
+      AZURE_TENANT_ID: ${{ secrets.TEST_TENANT_ID }}
+      M365_ACCOUNT_NAME: ${{ secrets.TEST_USER_NAME }}
+      M365_ACCOUNT_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
+      M365_TENANT_ID: ${{ secrets.TEST_TENANT_ID_2 }}
+      CI_ENABLED: "true"
+      M365_ACCOUNT_COLLABORATOR: ${{ secrets.TEST_COLLABORATOR_USER_NAME }}
+      AZURE_DEVOPS_EXT_PAT: ${{ secrets.ADO_PAT }}
+      TEAMSFX_V3: "true"
+      TEAMSFX_TEMPLATE_PRERELEASE: "alpha"
+    strategy:
+      fail-fast: false
+      matrix:
+        cases: [ "./frontend/TestCreateTab.tests.ts", "./bot/ProvisionCommandAndResponseBot.tests.ts", "./bot/ProvisionCommandAndResponseBot.dotnet.tests.ts" ]
+    name: ${{ matrix.cases }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Setup node
+        uses: actions/setup-node@v2.1.2
+        with:
+          node-version: 14
+
+      - name: Setup .net
+        uses: actions/setup-dotnet@v2
+        with:
+          dotnet-version: 6.0.x
+
+      - name: Download Simple Auth bits
+        uses: nick-fields/retry@v2
+        with:
+          timeout_minutes: 10
+          max_attempts: 5
+          shell: pwsh
+          command: |
+            ./.github/scripts/download-simpleauth.sh
+
+      - name: Setup project
+        uses: nick-fields/retry@v2
+        with:
+          timeout_minutes: 10
+          max_attempts: 5
+          command: |
+            npm run setup
+
+      - name: Download CLI
+        uses: actions/download-artifact@v3
+        with:
+          name: Teamsfx-cli
+
+      - name: Install CLI
+        run: |
+          npm install -g teamsfx-cli.tgz
+
+      - name: print system info
+        run: |
+          lscpu
+
+      - name: run test
+        working-directory: packages/cli/tests/e2e
+        run: |
+          file=`find . -wholename "${{ matrix.cases }}"`
+          if [ -z "$file" ]; then
+            echo "can't find target case in $file"
+            exit 1
+          else
+            npx mocha --reporter mochawesome --timeout 1200000 $file
+          fi
+
   execute-case:
     if: ${{ needs.setup.outputs.cases }}
     env:
