chore: v3 e2e testing (#6891)
* chore: v3 e2e testing

diff --git a/.github/workflows/e2e-test.yml b/.github/workflows/e2e-test.yml
--- a/.github/workflows/e2e-test.yml
+++ b/.github/workflows/e2e-test.yml
@@ -268,10 +268,8 @@ jobs:
           version=$(node -p -e "require('./packages/cli/package.json').version")
           npx ts-node .github/scripts/testPlan.ts sync ./packages/cli/tests/e2e/mochawesome-report/mochawesome.json cli $version
 
-  tear-down:
-    if: ${{ always() && github.event_name == 'schedule' }}
-    needs: execute-case
-    runs-on: ubuntu-latest
+  v3-execute-case:
+    if: ${{ needs.setup.outputs.cases }}
     env:
       AZURE_ACCOUNT_NAME: ${{ secrets.TEST_USER_NAME }}
       AZURE_ACCOUNT_OBJECT_ID: ${{ secrets.TEST_USER_OBJECT_ID }}
@@ -284,6 +282,15 @@ jobs:
       CI_ENABLED: "true"
       M365_ACCOUNT_COLLABORATOR: ${{ secrets.TEST_COLLABORATOR_USER_NAME }}
       AZURE_DEVOPS_EXT_PAT: ${{ secrets.ADO_PAT }}
+      TEAMSFX_V3: "true"
+    needs: setup
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        cases: ${{ fromJson(needs.setup.outputs.cases) }}
+    name: v3-${{ matrix.cases }}
+
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -293,6 +300,20 @@ jobs:
         with:
           node-version: 14
 
+      - name: Setup .net
+        uses: actions/setup-dotnet@v2
+        with:
+          dotnet-version: 6.0.x
+
+      - name: Download Simple Auth bits
+        uses: nick-fields/retry@v2
+        with:
+          timeout_minutes: 10
+          max_attempts: 5
+          shell: pwsh
+          command: |
+            ./.github/scripts/download-simpleauth.sh
+
       - name: Setup project
         uses: nick-fields/retry@v2
         with:
@@ -301,10 +322,56 @@ jobs:
           command: |
             npm run setup
 
-      - name: E2E Test clean
-        working-directory: packages/cli
+      - name: Download CLI
+        uses: actions/download-artifact@v3
+        with:
+          name: Teamsfx-cli
+
+      - name: Install CLI
         run: |
-          npm run test:e2e:clean
+          npm install -g teamsfx-cli.tgz
+
+      - name: print system info
+        run: |
+          lscpu
+
+      - name: run test
+        working-directory: packages/cli/tests/e2e
+        run: |
+          file=`find . -wholename "${{ matrix.cases }}"`
+          if [ -z "$file" ]; then
+            echo "can't find target case in $file"
+            exit 1
+          else
+            npx mocha --reporter mochawesome --timeout 1200000 $file
+          fi
+
+      - name: get job id
+        id: get-job-id
+        if: ${{ always() }}
+        uses: ayachensiyuan/get-action-job-id@v1.7
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          job-name: ${{ matrix.cases }}
+
+      - name: get report name
+        id: get-report-name
+        if: ${{ always() }}
+        run: |
+          name="${{ matrix.cases }}"
+          name="${name//'.tests.ts'/}"
+          name="${name//.\//}"
+          name="${name//\//_}"_${{ steps.get-job-id.outputs.jobId }}
+          echo "::set-output name=name::$name"
+
+      - name: Upload test report
+        uses: actions/upload-artifact@v2
+        if: ${{ failure() }}
+        with:
+          name: ${{ steps.get-report-name.outputs.name }}.json
+          path: |
+            ./packages/cli/tests/e2e/mochawesome-report/mochawesome.json
 
   report:
     if: ${{ always() && github.event_name == 'schedule' }}
@@ -326,11 +393,28 @@ jobs:
         id: list-jobs
         working-directory: packages/cli
         run: |
-          jobs=`curl \
-            -u :${{ secrets.GITHUB_TOKEN }} \
-            https://api.github.com/repos/OfficeDev/TeamsFx/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}/jobs?per_page=100`
+          page=1
+          jobs="[]"
 
-          cases=`echo $jobs| jq -r '.jobs[] | select(.name | contains("tests.ts")) | .name'`
+          while :
+          do
+
+            url=https://api.github.com/repos/OfficeDev/TeamsFx/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}/jobs\?per_page\=100\&page\=$page
+            resp=`curl -H "Accept: application/vnd.github.v3+json" -u:${{ secrets.GITHUB_TOKEN }} $url`
+
+            new_jobs=`echo $resp | jq -cr '.jobs'`
+
+            jobs=`jq -cr --slurp 'add' <(echo "$jobs") <(echo "$new_jobs")`
+
+            has_next=`curl -I -H "Accept: application/vnd.github.v3+json" -u:${{ secrets.GITHUB_TOKEN }} $url | grep -Fi "link:" || true | grep "rel=\"last\"" || true`
+            if [ -z "$has_next" ]; then
+              break
+            fi
+
+            page=$((page+1))
+          done
+
+          cases=`echo $jobs| jq -r '.[] | select(.name | contains("tests.ts")) | .name'`
 
           lists=""
           passed=0
@@ -343,6 +427,10 @@ jobs:
               continue
             fi
 
+            if [[ $case == *"v3-"* ]]; then
+              continue
+            fi
+
             file="tests/e2e/$case"
             elegant_path="${file//.\//}"
 
@@ -351,14 +439,14 @@ jobs:
               email=`grep '@author' $file | grep -i -o '[A-Z0-9._%+-]\+@[A-Z0-9.-]\+\.[A-Z]\{2,4\}'`
             fi
 
-            status=`echo $jobs | jq --arg case $case -r '.jobs[] | select(.name == $case ) | .conclusion'`
+            status=`echo $jobs | jq --arg case $case -r '.[] | select(.name == $case ) | .conclusion'`
 
             if [[ ! -z "$email" && ! "$emails" == *"$email"* && "$status" == "failure" ]]; then
               emails="$emails;$email"
             fi
 
-            started_at=`echo $jobs | jq --arg case $case -r '.jobs[] | select(.name == $case ) | .steps[] | select(.name == "run test") | .started_at'`
-            completed_at=`echo $jobs | jq --arg case $case -r '.jobs[] | select(.name == $case ) | .steps[] | select(.name == "run test") | .completed_at'`
+            started_at=`echo $jobs | jq --arg case $case -r '.[] | select(.name == $case ) | .steps[] | select(.name == "run test") | .started_at'`
+            completed_at=`echo $jobs | jq --arg case $case -r '.[] | select(.name == $case ) | .steps[] | select(.name == "run test") | .completed_at'`
             duration=`dateutils.ddiff $started_at $completed_at -f "%Mm %Ss"`
 
             author=""
@@ -377,14 +465,14 @@ jobs:
               label="<span style=\\\"background-color: #dc322f;color:white;font-weight:bold;\\\">FAILED</span>"
             fi
 
-            job_id=`echo $jobs| jq --arg case $case -r '.jobs[] | select(.name == $case ) | .id'`
+            job_id=`echo $jobs| jq --arg case $case -r '.[] | select(.name == $case ) | .id'`
             metrics_file=`find ~/artifacts -wholename "*${job_id}_metrics/output.txt"`
             slow_count=0
             if [ ! -z "$metrics_file" ]; then
               slow_count=`grep -c '"severity":"slow"' $metrics_file || true`
             fi
 
-            url=`echo $jobs | jq --arg case $case -r '.jobs[] | select(.name == $case ) | .html_url'`
+            url=`echo $jobs | jq --arg case $case -r '.[] | select(.name == $case ) | .html_url'`
             url="<a href=\\\"$url\\\">$elegant_path</a>"
 
             target_type="TS/JS"
@@ -434,3 +522,191 @@ jobs:
               "subject": "${{ steps.list-jobs.outputs.subject }}",
               "apiKey": "${{ secrets.MAIL_API_KEY }}"
             }
+
+  v3-report:
+    if: ${{ always() && github.event_name == 'schedule' }}
+    needs: v3-execute-case
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Install Dateutils
+        run: |
+          sudo apt install dateutils
+
+      - uses: actions/download-artifact@v3
+        with:
+          path: ~/artifacts
+
+      - name: List jobs
+        id: list-jobs
+        working-directory: packages/cli
+        run: |
+          page=1
+          jobs="[]"
+
+          while :
+          do
+
+            url=https://api.github.com/repos/OfficeDev/TeamsFx/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}/jobs\?per_page\=100\&page\=$page
+            resp=`curl -H "Accept: application/vnd.github.v3+json" -u:${{ secrets.GITHUB_TOKEN }} $url`
+
+            new_jobs=`echo $resp | jq -cr '.jobs'`
+
+            jobs=`jq -cr --slurp 'add' <(echo "$jobs") <(echo "$new_jobs")`
+
+            has_next=`curl -I -H "Accept: application/vnd.github.v3+json" -u:${{ secrets.GITHUB_TOKEN }} $url | grep -Fi "link:" || true | grep "rel=\"last\"" || true`
+            if [ -z "$has_next" ]; then
+              break
+            fi
+
+            page=$((page+1))
+          done
+
+          cases=`echo $jobs| jq -r '.[] | select(.name | contains("tests.ts")) | .name'`
+
+          lists=""
+          passed=0
+          failed=0
+
+          emails="vsciotadt@microsoft.com;v-helzha@microsoft.com;v-ivanchen@microsoft.com"
+          while IFS= read -r case;
+          do
+            if [ -z "$case" ]; then
+              continue
+            fi
+
+            if [[ $case != *"v3-"* ]]; then
+              continue
+            fi
+
+            file="tests/e2e/${case/v3-/}"
+            elegant_path="${file//.\//}"
+
+            email=""
+            if grep -q "@author" $file; then
+              email=`grep '@author' $file | grep -i -o '[A-Z0-9._%+-]\+@[A-Z0-9.-]\+\.[A-Z]\{2,4\}'`
+            fi
+
+            status=`echo $jobs | jq --arg case $case -r '.[] | select(.name == $case ) | .conclusion'`
+
+            if [[ ! -z "$email" && ! "$emails" == *"$email"* && "$status" == "failure" ]]; then
+              emails="$emails;$email"
+            fi
+
+            started_at=`echo $jobs | jq --arg case $case -r '.[] | select(.name == $case ) | .steps[] | select(.name == "run test") | .started_at'`
+            completed_at=`echo $jobs | jq --arg case $case -r '.[] | select(.name == $case ) | .steps[] | select(.name == "run test") | .completed_at'`
+            duration=`dateutils.ddiff $started_at $completed_at -f "%Mm %Ss"`
+
+            author=""
+            if [ -z "$email" ]; then
+              author="N/A"
+            else
+              author="<a href=\\\"mailto:$email\\\"><span>$email</span></a>"
+            fi
+
+            lable=""
+            if [ "$status" == "success" ]; then
+              passed=$((passed+1))
+              label="<span style=\\\"background-color:#2aa198;color:white;font-weight:bold;\\\">PASSED</span>"
+            else
+              failed=$((failed+1))
+              label="<span style=\\\"background-color: #dc322f;color:white;font-weight:bold;\\\">FAILED</span>"
+            fi
+
+            job_id=`echo $jobs| jq --arg case $case -r '.[] | select(.name == $case ) | .id'`
+            metrics_file=`find ~/artifacts -wholename "*${job_id}_metrics/output.txt"`
+            slow_count=0
+            if [ ! -z "$metrics_file" ]; then
+              slow_count=`grep -c '"severity":"slow"' $metrics_file || true`
+            fi
+
+            url=`echo $jobs | jq --arg case $case -r '.[] | select(.name == $case ) | .html_url'`
+            url="<a href=\\\"$url\\\">$elegant_path</a>"
+
+            target_type="TS/JS"
+            if [[ $case == *".dotnet."* ]]; then
+              target_type=".NET"
+            fi
+
+            core_version="V1/V2"
+            if [[ $case == *".v3."* ]]; then
+              core_version="V3"
+            fi
+
+            row="<tr> <td style=\\\"text-align: left;\\\">$url</td> <td style=\\\"text-align: center;\\\">$target_type</td> <td style=\\\"text-align: center;\\\">$core_version</td> <td style=\\\"text-align: center;\\\">$label</td> <td style=\\\"text-align: center;\\\">$author</td> <td style=\\\"text-align: center;\\\">$duration</td> <td style=\\\"text-align: center;\\\">$slow_count</td> </tr>"
+
+            if [ "$status" == "success" ]; then
+              lists="$lists $row"
+            else
+              lists="$row $lists"
+            fi
+
+          done <<< $cases
+
+          body="<table class=\\\"w3-table w3-striped w3-bordered\\\"> <tr> <th>CASE</th> <th>TARGET TYPE</th> <th>CORE VERSION</th> <th>STATUS</th> <th>AUTHOR</th> <th>DURATION</th> <th>SLOW METHOD( > 20ms )</th> </tr> $lists </table> <br /> The detail can be found here: <a> https://github.com/OfficeDev/TeamsFx/actions/runs/${{ github.run_id }} </a>"
+
+          total=$((passed+failed))
+
+          subject="TeamsFx V3 E2E Test Report ($passed/$total Passed)"
+          if [ $failed -gt 0 ]; then
+            subject="[FAILED] $subject"
+          else
+            subject="[PASSED] $subject"
+          fi
+
+          echo "::set-output name=body::$body"
+          echo "::set-output name=to::$emails"
+          echo "::set-output name=subject::$subject"
+
+      - name: Send E-mail to the whole team
+        uses: satak/webrequest-action@master
+        with:
+          url: https://prod-30.eastus.logic.azure.com:443/workflows/9aa865da96054bd89749c2d4ce68df8e/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=uIoB06NUHSnKoZeWjNDI9t4rrhbTBKxJNiBtDoMRSQs
+          method: POST
+          payload: |
+            {
+              "to": "haolong@microsoft.com;wenyutang@microsoft.com",
+              "body": "${{ steps.list-jobs.outputs.body }}",
+              "subject": "${{ steps.list-jobs.outputs.subject }}",
+              "apiKey": "${{ secrets.MAIL_API_KEY }}"
+            }
+
+  tear-down:
+    if: ${{ always() && github.event_name == 'schedule' }}
+    needs: [execute-case, v3-execute-case]
+    runs-on: ubuntu-latest
+    env:
+      AZURE_ACCOUNT_NAME: ${{ secrets.TEST_USER_NAME }}
+      AZURE_ACCOUNT_OBJECT_ID: ${{ secrets.TEST_USER_OBJECT_ID }}
+      AZURE_ACCOUNT_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
+      AZURE_SUBSCRIPTION_ID: ${{ secrets.TEST_SUBSCRIPTION_ID }}
+      AZURE_TENANT_ID: ${{ secrets.TEST_TENANT_ID }}
+      M365_ACCOUNT_NAME: ${{ secrets.TEST_USER_NAME }}
+      M365_ACCOUNT_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
+      M365_TENANT_ID: ${{ secrets.TEST_TENANT_ID_2 }}
+      CI_ENABLED: "true"
+      M365_ACCOUNT_COLLABORATOR: ${{ secrets.TEST_COLLABORATOR_USER_NAME }}
+      AZURE_DEVOPS_EXT_PAT: ${{ secrets.ADO_PAT }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Setup node
+        uses: actions/setup-node@v2.1.2
+        with:
+          node-version: 14
+
+      - name: Setup project
+        uses: nick-fields/retry@v2
+        with:
+          timeout_minutes: 10
+          max_attempts: 5
+          command: |
+            npm run setup
+
+      - name: E2E Test clean
+        working-directory: packages/cli
+        run: |
+          npm run test:e2e:clean
