chore: support v3 test (#7059)
* chore: support v3 test

* chore: update

diff --git a/.github/workflows/e2e-test.yml b/.github/workflows/e2e-test.yml
--- a/.github/workflows/e2e-test.yml
+++ b/.github/workflows/e2e-test.yml
@@ -6,6 +6,10 @@ on:
       cases:
         description: 'specific cases to be excuted. Sample: ["./aad/a.tests.ts", "./bot/b.tests.ts"]. Set empty to run all cases'
         required: false
+      v3:
+        description: 'set v3 feature flag turn on for testing(true or false)'
+        required: false
+        default: 'false'
   schedule:
     - cron: "0 0 * * *"
   pull_request:
@@ -285,6 +289,21 @@ jobs:
 
       - name: run test
         working-directory: packages/cli/tests/e2e
+        run: |
+          file=`find . -wholename "${{ matrix.cases }}"`
+          if [ -z "$file" ]; then
+            echo "can't find target case in $file"
+            exit 1
+          else
+            npx mocha --reporter mochawesome --timeout 1200000 $file
+          fi
+
+      - name: run test for v3
+        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.v3 != 'false' }}
+        working-directory: packages/cli/tests/e2e
+        env:
+          TEAMSFX_V3: "true"
+          TEAMSFX_TEMPLATE_PRERELEASE: "alpha"
         run: |
           file=`find . -wholename "${{ matrix.cases }}"`
           if [ -z "$file" ]; then
