chore: exit 1 if case's not found

diff --git a/.github/workflows/e2e-test.yml b/.github/workflows/e2e-test.yml
--- a/.github/workflows/e2e-test.yml
+++ b/.github/workflows/e2e-test.yml
@@ -205,7 +205,10 @@ jobs:
         working-directory: packages/cli/tests/e2e
         run: |
           file=`find . -wholename "${{ matrix.cases }}"`
-          if [ ! -z "$file" ]; then
+          if [ -z "$file" ]; then
+            echo "can't find target case in $file"
+            exit 1
+          else
             npx mocha --reporter mochawesome --timeout 900000 $file
           fi
 
